---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: demo
spec:
  encryptedData:
    JWT_SECRET: AgB+SKwmDthdAucHK6iYddHqLySf/t103N+QRDGSJhls6VhNrusIYYn/xrJWD1DcuCeBorZW58AIM4Y8NGUb+OHAkj8k7TzycTUoJQR5WtTff9T6MrqD7RmMoofKKI1vfwQKfre6KXLWiEKEcSx8SwwGBZkKDkXtaHLJrbroTzMnLCYRbUxtz3hj2wKSs64AtDKN8kSrqrZBD0tgMI177jVI3Sap+OB93pMmK+FlyBkt2YswRwrhksmt4QVCRcjFteoYNTUK7GWTXK2yAkBZjtkccZABRznBqfWZtLyBOs+8N+SGqDbGhLSYE2XJtV5o/JNY6EOEO/expj99wc9RqntFfk+QZ8CD2P8wRemPgV4aQccVC5/hd5VfRFDUHBXDUnkRKeDtcoBPFltsbire30Y08lKV6WnOSwVkd5SdIH8TC2PuxrrJve2eYpOCJNBLrI0Bq0KL+bTirTobY59xzJzQWL+oOUAsAzXW0+1/11zT3ez0hOTF4LxwVYMNejUyiCLoMn9pzCBuWW7pNQwYb/zvPyXrOx05lxQ95xUT7b2IsH2rAnPmxTOijNjlV11O5o+GX93sL0Ga7WSjbR1zBBXZlsAaTJlYYPTMoZYr0ujjGngGVoWSnL8JnYBiXrM467KLLOSPHOjbqbbTbSA98/fp2vnO6VQDqdnQOgdCXh7KAf9LU/Ou2IQd1V5OFKUiRi9WLHxOQ6mTTyal
    PGPASSWORD: AgChy2G/KNoWfhXwP3J8kyuJLUTwDw3f21JwQc6yFQI1vzjS4LU/nIfqfkK1eyMwSjzD6ybidvQNvh/3Cf2fvVGV0s2hJKJ3bTbZYOq6p5YAC1KX8wEJgOsvWN+Mq1h2dczFuFmcu2l/JeG4VC5Cf8xz5N0x/v2qDkyzDQFuh7dqCw8KCsRwQPASOIfmuGbOzxd3QP0THjRZulvYNI5R9EWYir8py7gTkSNVgGjWWpCL+Jj4ltNXL50DKCiLCFIKF/qRJm99INVGDTbw+81oLZxez2ZPgPxwnE694wv+W4c+wtUfcCeJcf+XWKLq4xzgpfimexkEohzEIsFG3GwxXyE2lRNTWJZrFF9extBpGcgPPO0Y8OeBSXhvm403osJ2m0Jqy8Q9AMzTVpkkFFuY0zr8riIXj4zAtaGJvQwIx2UfnQ2ocnwtFdvN+8px6L5csSo/fW4hwZMm8CeSTctTbgzwpz8GO9+4zontSm0cN6dGpBaFW9U3Yt6KIceIbZrlOd/aTTKIWd+X47HqC4tiWKeqibDi/BWoo0boxLGK/R7EhTe9XJULPrZ8IOpdnXhoaj60gasJeqN+WjYtX2F2emPzNHf1Manl0HmlmCwen5D372nSwFnyrIvEFCASoH71gqfndaRHyIFVqhQekFZangbH/AhWZ7LwZKK7cxkmEJPiE/SI1lGyO0I1UVOEuopzt7FD2NONTwwg
  template:
    metadata:
      name: auth-secret
      namespace: demo
    type: Opaque
