---
# Source: catalog/templates/6-podDistri.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: catalog-pdb
  namespace: demo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: catalog
---
# Source: catalog/templates/4-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
data:
  PGUSER: "appuser"
  PGHOST: "my-postgresql.postgres.svc.cluster.local"
  PGDATABASE: "mv100db"
  PGPORT: "5432"

  REDIS_URL: "redis-master.redis.svc.cluster.local:6379"

  KAFKA_BROKERS: "kafka.kafka.svc.cluster.local:9092"
  KAFKA_CLIENT_ID: "catalog-service"
  KAFKA_TOPIC_PRODUCTS: "mv100db.public.products"

  LOG_LEVEL: "info"
  PORT: "3001"

  FRONTEND_URL: "http://frontend.localdev.me"

  OTEL_PROM_PORT: "9464"
---
# Source: catalog/templates/8-catalog-dash-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-stable-dashboard
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
  annotations:
    grafana_folder: "Catalog"
data:
  catalog-stable.json: |
    {
      "title": "Catalog Stable – DevOps & App Dashboard",
      "schemaVersion": 36,
      "version": 5,
      "refresh": "10s",
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "panels": [

        {
          "type": "gauge",
          "title": "Success Rate (%)",
          "gridPos": { "x": 0, "y": 0, "w": 8, "h": 6 },
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "(sum(rate(istio_requests_total{reporter=\"source\",destination_service_name=\"catalog-stable\" ,response_code=~\"2..\"}[5m])) / sum(rate(istio_requests_total{reporter=\"source\",destination_service_name=\"catalog-stable\"}[5m]))) * 100",
              "refId": "A"
            }
          ],
          "fieldConfig": { "defaults": { "unit": "percent" } }
        },

        {
          "type": "gauge",
          "title": "4xx Error Rate (%)",
          "gridPos": { "x": 8, "y": 0, "w": 8, "h": 6 },
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "(sum(rate(istio_requests_total{reporter=\"source\",destination_service_name=\"catalog-stable\",response_code=~\"4..\"}[5m])) / sum(rate(istio_requests_total{reporter=\"source\",destination_service_name=\"catalog-stable\"}[5m]))) * 100",
              "refId": "B"
            }
          ],
          "fieldConfig": { "defaults": { "unit": "percent" } }
        },

        {
          "type": "gauge",
          "title": "5xx Error Rate (%)",
          "gridPos": { "x": 16, "y": 0, "w": 8, "h": 6 },
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "(sum(rate(istio_requests_total{reporter=\"source\",destination_service_name=\"catalog-stable\",response_code=~\"5..\"}[5m])) / sum(rate(istio_requests_total{reporter=\"source\",destination_service_name=\"catalog-stable\"}[5m]))) * 100",
              "refId": "C"
            }
          ],
          "fieldConfig": { "defaults": { "unit": "percent" } }
        },

        {
          "type": "gauge",
          "title": "P95 Latency (ms)",
          "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "histogram_quantile(0.95,sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\",destination_service_name=\"catalog-stable\"}[5m])) by (le))",
              "refId": "D"
            }
          ],
          "fieldConfig": { "defaults": { "unit": "ms" } }
        },

        {
          "type": "gauge",
          "title": "CPU Usage (%)",
          "gridPos": { "x": 12, "y": 6, "w": 6, "h": 6 },
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "100 * sum(rate(container_cpu_usage_seconds_total{namespace=\"demo\",pod=~\"catalog-.*\",container!=\"POD\"}[2m])) / sum(kube_pod_container_resource_limits{namespace=\"demo\",pod=~\"catalog-.*\",resource=\"cpu\"})",
              "refId": "E"
            }
          ],
          "fieldConfig": { "defaults": { "unit": "percent" } }
        },

        {
          "type": "gauge",
          "title": "Memory Usage (%)",
          "gridPos": { "x": 18, "y": 6, "w": 6, "h": 6 },
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "100 * sum(container_memory_working_set_bytes{namespace=\"demo\",pod=~\"catalog-.*\",container!=\"POD\"}) / sum(kube_pod_container_resource_limits{namespace=\"demo\",pod=~\"catalog-.*\",resource=\"memory\"})",
              "refId": "F"
            }
          ],
          "fieldConfig": { "defaults": { "unit": "percent" } }
        },

        {
          "type": "stat",
          "title": "Products Created / min",
          "gridPos": { "x": 0, "y": 12, "w": 8, "h": 5 },
          "datasource": "Prometheus",
          "targets": [{ "expr": "rate(catalog_products_created_total[5m]) * 60", "refId": "G" }]
        },

        {
          "type": "stat",
          "title": "Products Updated / min",
          "gridPos": { "x": 8, "y": 12, "w": 8, "h": 5 },
          "datasource": "Prometheus",
          "targets": [{ "expr": "rate(catalog_products_updated_total[5m]) * 60", "refId": "H" }]
        },

        {
          "type": "stat",
          "title": "Products Deleted / min",
          "gridPos": { "x": 16, "y": 12, "w": 8, "h": 5 },
          "datasource": "Prometheus",
          "targets": [{ "expr": "rate(catalog_products_deleted_total[5m]) * 60", "refId": "I" }]
        },

        {
          "type": "stat",
          "title": "Cache Hits / min",
          "gridPos": { "x": 0, "y": 17, "w": 8, "h": 5 },
          "datasource": "Prometheus",
          "targets": [{ "expr": "sum(rate(catalog_cache_hits_total[5m])) * 60", "refId": "J" }]
        },

        {
          "type": "stat",
          "title": "Cache Misses / min",
          "gridPos": { "x": 8, "y": 17, "w": 8, "h": 5 },
          "datasource": "Prometheus",
          "targets": [{ "expr": "sum(rate(catalog_cache_misses_total[5m])) * 60", "refId": "K" }]
        },

        {
          "type": "stat",
          "title": "Kafka Publish Failures / min",
          "gridPos": { "x": 16, "y": 17, "w": 8, "h": 5 },
          "datasource": "Prometheus",
          "targets": [{ "expr": "sum(rate(catalog_kafka_publish_failures_total[5m])) * 60", "refId": "L" }]
        }
      ]
    }
---
# Source: catalog/templates/2-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: catalog-canary
  namespace: demo
spec:
  ports:
    - port: 3001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: catalog
---
# Source: catalog/templates/2-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: catalog-stable
  namespace: demo
spec:
  ports:
    - port: 3001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: catalog
---
# Source: catalog/templates/5-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalog-hpa
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: catalog

  minReplicas: 1
  maxReplicas: 10

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
---
# Source: catalog/templates/1-gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: api-gateway
  namespace: demo
spec:
  selector:
    istio: gateway

  servers:
    # HTTP
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "api.localdev.me"
---
# Source: catalog/templates/9-prometheus-alerte-rules.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: catalog-stable-rules
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  groups:
    - name: istio-catalog-stable-alerts
      rules:

        # ----------------------------------------------------
        # 1. Stable Success Rate Alert (<95%)
        # ----------------------------------------------------
        - alert: IstioCatalogStableLowSuccessRate
          expr: |
            (
              sum(rate(istio_requests_total{
                reporter="destination",
                destination_service_name="catalog-stable",
                response_code=~"2.."
              }[5m]))
              /
              sum(rate(istio_requests_total{
                reporter="destination",
                destination_service_name="catalog-stable"
              }[5m]))
            ) * 100 < 90
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Stable service success rate is low"
            description: "Success rate for catalog-stable dropped below 90%."

        # ----------------------------------------------------
        # 2. Stable 5xx Error Rate Alert (>1%)
        # ----------------------------------------------------
        - alert: IstioCatalogStableHigh5xxRate
          expr: |
            sum(rate(istio_requests_total{
              reporter="destination",
              destination_service_name="catalog-stable",
              response_code=~"5.."
            }[5m]))
            /
            sum(rate(istio_requests_total{
              reporter="destination",
              destination_service_name="catalog-stable"
            }[5m]))
            > 0.01
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Stable service 5xx error rate is too high"
            description: "More than 0% of requests to catalog-stable are 5xx errors."

        # ----------------------------------------------------
        # 3. Stable P95 Latency Alert (>500ms)
        # ----------------------------------------------------
        - alert: IstioCatalogStableHighP95Latency
          expr: |
            histogram_quantile(
              0.95,
              sum(rate(istio_request_duration_milliseconds_bucket{
                reporter="destination",
                destination_service_name="catalog-stable"
              }[5m])) by (le)
            ) > 800
          for: 3m
          labels:
            severity: warning
          annotations:
            summary: "Stable service P95 latency is high"
            description: "P95 latency for catalog-stable exceeded 800ms."
---
# Source: catalog/templates/7-rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: catalog
  namespace: demo
spec:
  replicas: 1
  revisionHistoryLimit: 1

  selector:
    matchLabels:
      app: catalog

  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: catalog
        istio: monitor

    spec:
      containers:
        - name: catalog
          image: "devopsflow999/catalog:dev-v0.1.4"
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: catalog-config
            - secretRef:
                name: app-secrets

          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
            - name: metrics
              containerPort: 9464
              protocol: TCP

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

  strategy:
    canary:
      stableService: catalog-stable
      canaryService: 

      trafficRouting:
        istio:
          virtualService:
            name: 
            routes:
              - 

      steps:
---
# Source: catalog/templates/3-virtualservice.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: catalog-vsvc
  namespace: demo
spec:
  hosts:
    - "api.localdev.me"
  gateways:
    - api-gateway

  http:
    # Canary route (must be first)
    - name: catalog-canary
      match:
        - uri:
            prefix: "/catalog/"
          headers:
            x-canary:
              exact: "true"
        - uri:
            exact: "/catalog"
          headers:
            x-canary:
              exact: "true"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: catalog-canary
            port:
              number: 3001

    # Stable route
    - name: catalog-stable
      match:
        - uri:
            prefix: "/catalog/"
        - uri:
            exact: "/catalog"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: catalog-stable
            port:
              number: 3001
          weight: 100
        - destination:
            host: catalog-canary
            port:
              number: 3001
          weight: 0
