replicaCount: 1

image:
  tag: dev-v0.1.4

##

env:
  PGUSER: appuser
  PGHOST: my-postgresql.postgres.svc.cluster.local
  PGDATABASE: mv100db
  PGPORT: "5432"

  REDIS_URL: redis-master.redis.svc.cluster.local:6379

  KAFKA_BROKERS: kafka.kafka.svc.cluster.local:9092
  KAFKA_CLIENT_ID: catalog-service
  KAFKA_TOPIC_PRODUCTS: mv100db.public.products

  LOG_LEVEL: info
  PORT: "3001"

  FRONTEND_URL: http://frontend.localdev.me

  OTEL_PROM_PORT: "9464"



namespace: demo

host: api.localdev.me

istio:
  gateway: api-gateway
  tls:
    enabled: false
    secretName: api-travelersources-tls-secret


alerts:
  successRateThreshold: 90
  latencyP95Threshold: 800


configMapName: catalog-config
secretName: app-secrets

hpa:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilization: 60

pdb:
  minAvailable: 1