---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secrets
  namespace: dev
spec:
  encryptedData:
    JWT_SECRET: AgCFCXtpVFJf/r+d71FEG2JxRjGOtjBxd+9OIbLNU3uAk/xsP+Gfdtmq5j7rq4D8Q/Gi3SJ/E98xyw+L6ef+by3hQe7OYbYG4BhgIigzQzuxyXxWXM6OjoOCvWaW5jT0zDSl0f15mkMVzX1tmokcrzGCWKspeifyrl4InP5ZFNhfa2TFCNNsGdr8uKFsVSB9/KSCqQ+QLOrG0lO68hIVshBnQRfJKu0t4Yi1jdvBOd1UhWD6L+oeB8DmX9+u1AqEsNQWpHxHn8VKQZ1q64wo+48uedJqcMYGBDHqFNXKY2uCZOF94xUIGOFnvCJtdpW4mja9V1pI9oIFas6c9Lq4+0OcmGqKogFxX1UDK04NneJ2oVsAbrGCfegcKhPcYveXBZb2Qqv7GbQhn940JOpmS4uGkFvQWkxcYriC1ds/KwUGrnOpxRWjwfagceHn2NfJkJjdcBE9XEe2vTRYdyorqQdtAd4wD6n4ToCP22jKAmGbGhPTey3LLOTuXHkhtVb/Ne9u5+NeGZvSREE49ah1TwsHqiWSfpVuRBX4uP9wsriZfTihnqMz3B8P7e//jxMaL385V2SHNIcchgy6WRUNO6hCSDh9D0UP5cjjRPE2xD0R8ub6CGEGi7KO5ZsnnMcvNL3QprDLKRNQohVNLn6etZMhVDFvGGu0KZypRphJyqIiieLtW+g1OKH6usC5uBkARTQ/TlnNH//Ca86p
    PGPASSWORD: AgAY/ZPml0IGdSQxBOVx2ZAvz5DAGUV8Ew4tXm0bz6IkZvdDwGHY978eP5JT/I7lpwwfCJE+UzIbMvvlSlhMJNV0mnUGsNCWP+REUvdCUo4s0rXQYSlcuRdlfpjEnaVAHc+kn6xKI1ZLA2tDzYX77X1OS4jGDELPRbZ2ozDHP7GUAYrwhOu5kN154pe8FZ7W7HXE47n9Sd73XbFxZeKCRqsOebCkdNOT1ZXAe2LgZ0suypfSletELV27jodybtFgshn1WFeK+jf9M/bcGuaNBU/HRA00mcCK/MHaOVoL/nwpcqjvlGkOYfyzdOeNpY9yeTHenihcreEFcrId/EvJMMRc1f74WI821bjCtzLDBvXBuR7eVosrs3oe2JHGgExqpBwDlBdmJ1QfyvTUuVn/RQKRYLQi81rwIrSmqU2ldx9M5Ll6NqhlpU56GKrzehnhP9rx6mqYr/d/slcyqrp0I7eeyYAB7RGo/A3i/7ZLtSMjr1hAJqUXCiQJzFn26N/AhUWmKjxtv8acAF0y5yC28kT7kodwXBjC1GqGwkLXK+wNxIUPEtP4uly+Be3Bu6KAREJH6CEW6270tt6j1U6iAMpJUB8dnZsKohUegScTcCaD46dTmhxF31tQIDAO+EqqSA03dLPUshbVp1eGfLrBkCS0zjj6qClfdqWycO0eMfTIFc+LJs6qDbmx48GuWRgUn9SYgFWGUxCH
  template:
    metadata:
      name: demo-secrets
      namespace: dev
    type: Opaque
