apiVersion: v1
kind: Service
metadata:
  name: cart-canary
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  ports:
    - port: {{ .Values.service.port | default 3003 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cart

---
apiVersion: v1
kind: Service
metadata:
  name: cart-stable
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  ports:
    - port: {{ .Values.service.port | default 3003 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cart
