apiVersion: v1
kind: Service
metadata:
  name: frontend-canary
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
      name: http

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-stable
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
      name: http
