apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend-vsvc
  namespace: demo
spec:
  hosts:
    - {{ .Values.istio.host }}
  gateways:
    - {{ .Values.istio.gateway }}
  http:
    - name: canary-debug
      match:
        - headers:
            x-canary:
              exact: "true"
      route:
        - destination:
            host: frontend-canary
          weight: 100
    - name: primary
      route:
        - destination:
            host: frontend-stable
          weight: 100
        - destination:
            host: frontend-canary
          weight: 0
