---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-secrets
  namespace: dev
spec:
  encryptedData:
    VITE_STRIPE_KEY: AgB03M5ablVivkvsdzRSOzJ3WceIta/ui4VpUsskbI6zN1kWNgmoCySDDsKt5EK0ZR5NoxOA7z38sa+0oVqRCAtuJJ+ir38Mu7F42SRHacEnVXYzC/Eyhv+w3040M8aujCmT37fvxGWZLWL7QM6QqyKN9MpXF3eQ7xLUATyVkHfqB1Ki0IRQJl5V6KMzlckQbbYJJcYSmVq5uMRT/pqkj6Gdxf4Rc1McusMbsHzbTkFX970uom8Q6WkyQI8dJPeYpO2kWNb1oDv7UOmjrjwnhipFFpEZbJ0xmsnfhZSY06vrppsNyzLvLsiRh7xIM5WZ9pX4t1nlOD3YvOlTeJdLXsOZpkv8tweqqWHppPNeKoqYVTCr0cqpLa/QzIG3lfRb9DpVPi6vInUfPqhyUa9TSbqt4kABF4g0g5DXub0WZQ4umcrBh6/8LXz62w4Rc081IeDzWKxBe3QoBq+2Y4hwgegKiMiyX/oElUC+zTzcPAPRt6Tu7U8er5I5PM4ZGAAzsWKQdoDazmznyJEPlXssby3+xDFU5i6l2SRuNx00apYUeXLZjcWRwiZPZzMK4/KZoj4cEPZxkkM0nY0yq1MuAjqYmXCrm3lmpAmoUv2D4dzwYTLc+a5tg4ZldKHYXso78PgRI8VT4Qf87+OeQQ8/bXzTWxZoVwWnHNZeFvMzDd296jW/+Cn+UQCQvRtuMz7fxoP2Yt27nF9WCsRI2yMoyI9PTysnheBm43X8tPYUPGXCchQcSQMs+xP8goJnbFflD1eVs1GnQgCMnZjICZ24237ALGeGVO/icltE8Km+F2hxePeVq65zfUATzTzKuUNWtawDptRTsUlEtEoG1A==
  template:
    metadata:
      name: frontend-secrets
      namespace: dev
