replicaCount: 2
image:
  repository: devopsflow999/frontend
  tag: "dev-v0.1.17"
  pullPolicy: IfNotPresent
service:
  port: 80
istio:
  host: frontend.localdev.me
  gateway: frontend-gateway
env:
  VITE_STRIPE_KEY: "" # Will be set from frontend-secrets
