apiVersion: v1
kind: Service
metadata:
  name: auth-canary
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  ports:
    - port: {{ .Values.service.port | default 3002 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: auth

---
apiVersion: v1
kind: Service
metadata:
  name: auth-stable
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  ports:
    - port: {{ .Values.service.port | default 3002 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: auth
