apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: auth-vsvc
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  hosts:
    - "{{ .Values.gateway.host | default "api.travelersources.com" }}"
  gateways:
    - {{ .Values.gateway.name | default "api-gateway" }}
  http:

    # Canary route must be first
    - name: auth-canary-debug
      match:
        - uri:
            prefix: "/auth/"
          headers:
            x-canary:
              exact: "true"
        - uri:
            exact: "/auth"
          headers:
            x-canary:
              exact: "true"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: auth-canary
            port:
              number: {{ .Values.service.port | default 3002 }}

    # Stable route
    - name: auth-route
      match:
        - uri:
            prefix: "/auth/"
        - uri:
            exact: "/auth"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: auth-stable
            port:
              number: {{ .Values.service.port | default 3002 }}
          weight: 100
        - destination:
            host: auth-canary
            port:
              number: {{ .Values.service.port | default 3002 }}
          weight: 0
