apiVersion: v1
kind: Service
metadata:
  name: catalog-canary
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  ports:
    - port: {{ .Values.service.port | default 3001 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: catalog

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-stable
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  ports:
    - port: {{ .Values.service.port | default 3001 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: catalog
