apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  PGUSER: {{ .Values.env.PGUSER | quote }}
  PGHOST: {{ .Values.env.PGHOST | quote }}
  PGDATABASE: {{ .Values.env.PGDATABASE | quote }}
  PGPORT: {{ .Values.env.PGPORT | quote }}

  REDIS_URL: {{ .Values.env.REDIS_URL | quote }}

  KAFKA_BROKERS: {{ .Values.env.KAFKA_BROKERS | quote }}
  KAFKA_CLIENT_ID: {{ .Values.env.KAFKA_CLIENT_ID | quote }}
  KAFKA_TOPIC_PRODUCTS: {{ .Values.env.KAFKA_TOPIC_PRODUCTS | quote }}

  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  PORT: {{ .Values.env.PORT | quote }}

  FRONTEND_URL: {{ .Values.env.FRONTEND_URL | quote }}

  OTEL_PROM_PORT: {{ .Values.env.OTEL_PROM_PORT | quote }}
