apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: {{ .Chart.Name }}

  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: {{ .Chart.Name }}
        istio: monitor

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config
            - secretRef:
                name: demo-secrets

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}

          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}

  strategy:
    canary:
      stableService: {{ .Chart.Name }}-stable
      canaryService: {{ .Chart.Name }}-canary

      trafficRouting:
        istio:
          virtualService:
            name: {{ .Chart.Name }}-vsvc
            routes:
              - {{ .Chart.Name }}-route

      steps:
{{- range .Values.canary.steps }}
        - setWeight: {{ .weight }}
        - pause: { duration: 20s }
{{- end }}
