apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-canary
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    app: {{ .Chart.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-stable
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    app: {{ .Chart.Name }}
