apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}-vsvc
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  hosts:
    - "{{ .Values.istio.host }}"
  gateways:
    - {{ .Values.istio.gateway }}

  http:

    # Canary route must be first
    - name: {{ .Chart.Name }}-canary-debug
      match:
        - uri:
            prefix: "/catalog/"
          headers:
            x-canary:
              exact: "true"
        - uri:
            exact: "/catalog"
          headers:
            x-canary:
              exact: "true"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: {{ .Values.canaryService }}
            port:
              number: {{ .Values.service.port }}

    # Stable route
    - name: {{ .Chart.Name }}-route
      match:
        - uri:
            prefix: "/catalog/"
        - uri:
            exact: "/catalog"
      rewrite:
        uri: "/"
      # corsPolicy:
      #   allowOrigins:
      #     - exact: "{{ .Values.frontendUrl }}"
      #   allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      #   allowHeaders: ["*"]
      #   allowCredentials: true
      #   maxAge: "1h"
      route:
        - destination:
            host: {{ .Values.stableService }}
            port:
              number: {{ .Values.service.port }}
          weight: 100
        - destination:
            host: {{ .Values.canaryService }}
            port:
              number: {{ .Values.service.port }}
          weight: 0

