namespace: dev

service:
  port: 3003

database:
  user: appuser
  host: my-postgresql.postgres.svc.cluster.local
  name: mv100db
  port: "5432"

redis:
  url: redis-master.redis.svc.cluster.local:6379

env:
  LOG_LEVEL: info

frontend:
  url: https://travelersources.com

otel:
  promPort: "9466"

hpa:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilization: 60

pdb:
  minAvailable: 1

namespace: demo

replicaCount: 1
revisionHistoryLimit: 1

image:
  repository: devopsflow999/cart
  tag: main-v0.1.1
  pullPolicy: IfNotPresent

service:
  port: 3003

metrics:
  port: 9466

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

strategy:
  steps:
    - weight: 10
      pause: {}
    - weight: 20
      pause:
        duration: 20s
    - weight: 30
      pause:
        duration: 20s
    - weight: 40
      pause:
        duration: 20s
    - weight: 50
      pause:
        duration: 20s
    - weight: 60
      pause:
        duration: 20s
    - weight: 70
      pause:
        duration: 20s
    - weight: 80
      pause:
        duration: 20s
    - weight: 90
      pause:
        duration: 20s

grafana:
  folder: "Cart Service"

monitoringNamespace: monitoring

prometheusRule:
  release: kube-prom-stack

strategy:
  stableService: cart-stable

alerts:
  successRateThreshold: 95
  successRateFor: 2m
  errorRateThreshold: 0.01
  errorRateFor: 2m
  latencyP95Threshold: 500
  latencyP95For: 3m
