---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secrets
  namespace: dev
spec:
  encryptedData:
    JWT_SECRET: AgBElQzdyo5vzRFe8bNgXsBq2uoeoFaOYC8D0RCigNHOugSDWPZ5qn2VOIkP9b7zZqJ4kxga+M0CzJGiyutu7saMaqM9dgIq/KtnBs8Xf019bjOn2/Qp7B/1Oc7SvmVV6sCNxTZy9HaoVGk8UJ6U2mlJAuEeTEolzCp7H38f8d0V4B6AM989a7jMyS2eOvNYrBdZgYeC1r9bamIvEDM9oj5txlTVdtkC7g+Qnfj9234wJr+CmBSjVoXOJcX202BnHJwTN3tfb80uddBhJ7tTtwoA5d985j8eUjGmtxx5TarE+xJ9l6IViysJwx7o+wPMMtdVydgTyQSUDWkN2Q0vSbDwlsnR4sJqziXDCwWIND982nqXxYK7T9Mq7Xe2xEkcM4PI0JD472gq5Snt9ZutUeDV+9gJEIVBDUzAdCDy/UoZLyrBtg1OCEzAEcAvEYyxGD1fRIeEM/5mdceEOUeoH8nalGPTcySExA0O4Xshle1yEfzHjPNSpNdxZdWhzWT330Qgdlp0yFp0wSTpqFQO1/gEKJJEENPgANWe2Iyz2Yi+4DGTEmmYvQw4CY0oRhG0U34Q2Br+x2cfMet/2h1DMgf8OB8O2wWDa8xpCvch3JTNQn5facXHTLrnO5aGzNG5zG3vsQt1WEctOiUEmpdtkn9TDBSbiu3Xqh6JeZVosC2fBtDn8HtcBgAhi+oliU8N4fybOzDCaCJwvk+u
    PGPASSWORD: AgC/jPWLKIBhqfF7LMqmgD9MYR1QmaGRoCVrfnPZCXcNpVxHcFB2g19Mc0RMqmaMqen7HLMrMy1cXffJYjKsyc3y6NFmfmIdAp/ZG+ioKCWvgHMPagp1k7toQaX/anhWNfQuriUasU/kTxzdjTnX9BqNfiW4wkT4kj9cbSX+coJ47H3iVYBpUzLPL5/GpbJxbTsbs6FuY+AUOnOCP307Kw/9+6XHbYZwVvF5ZET1JZePf20oxsER4RL2zU8ED8by76zAhl3W3+yD3RAVQw7E6/bxanG3Rbqo4EBTpc+PpIWptDni4JrR22KKSobkE68YFZvlL/ovsUx7Ofw19lT/rqixst9UnsHKuDh+Hp8k5uosp9Hs+yzSClwmxcBG8P0i7Ox0K4f64o29XvcMKQvco86u+dcB1onBQz6qOErd0cmikRUueRKhVSQQtTmJ5ucqLJlXU4Q1JW+Q8C8QiA+SFiuMav3FoCi+6iVi0xF1TD4fiohtr+IquGO+KxuZTF7r4Xz87dOIEnDemqjqpWfuOPE2Exwb5Vonp4nqPDCMa7f7VycjPY9OIE6brFtbiri1RZ416CiHZWDZ5j+Y5flTeqmy8vvFVVgR0LvRcm+C+RIPNIWkH1EPmm0H3+kK66XfhrGt6bthfSUWQETsJImhoPKuChsgaqSeXrX2VPqdscS/gADBqZ5koGYaVsrQOtKHlWmahW1VuhgH
  template:
    metadata:
      name: demo-secrets
      namespace: dev
    type: Opaque
