---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-secrets
  namespace: prod
spec:
  encryptedData:
    VITE_STRIPE_KEY: AgC1EnRtsbkPWS0ftOt7R5RPx/56/vm4Sak/W4W5rwGBa7bd5Bn08oHR4REgkmGxCoIBtWwNeSsQQTKdQXPmGE8RVbISt9/2/sMPG7TuXQyOAWM2+mLd2vPkNCKAAy5Z9AphT2a9JV/+ZYwm9EXKI0hSZ+/OE2uQH/8eu5jLPYva3npC2JvzWIKYOZaWM5WAtXD8OieW0Mtj7fvPwzE/EBkyASa09k4lGoGYD6+VBDJLPRDrs4faytrtPcZwUs57kUR5uz86h/dSKib2wTvOOtSwcUEUezgjqCQMM+PHJ/YKWOoacCqOLAcHUnG+tGXDNaem4llffrjk8RZLW57WxfY2PEhkURNXv+L46RYO8KyeUJuiW/ql8VOiK749sdWV9O5sFUlkJNuLRlSddMw+g4vaqYFLXGFSjZN5Hxq0Gfm4H5b62FhQKr+OmmBuvp041pMjDgGtE+qAhB+cBhXU+JyoSKagLqcWz74OKKWppZTl14DSTwE8tSBuk7BkxOH9vq4vP9IDwD+tBAm7N9FxUiGeEB+fCV+Iddp4lJzYePIQYAiPM5UFlU41lTYAdLGQB0ljP+d+Q3sKx8fOi5e7gmA+y7D7bYd87fsGdI6gd6Y+8yxT7BuxIjeH19fJ+gL9W5TYJEiyyRzKwJ2TmX1ZDA8HQOrsQZTfdabx+nI1W3wbzEii86lMO3rgXWd+UdRzc+pCCVpz8ocLTGuWfPozaOzxS+90/yNkM2dIBVSqWTZN0ERQ5iNNHbvxrSRvhyXT29OoUl9q3TNRzq1ynLoI6HIoOBjIBCNf+UNUWrXROS5nrWI/2MjYlj5tdY+kkuu0jge6III25hjdyPCrLQ==
  template:
    metadata:
      name: frontend-secrets
      namespace: prod
