apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - certificate.yaml
  - gateway.yaml
  - kyverno_rules.yaml
  # - secret.yaml  we gonna use eso instead of sealed secrets 
  - vs.yaml
  - cluster_issuer.yaml
  - mTLs.yaml
  - ClusterSecretStore.yaml
  - ExternalSecret.yaml
  - svc-monitor.yaml
  # - configmap-app.yaml  every mircoservice has it s own variables like port otel_pro_port ...
